### ISSUE TITLE
find a way to generate the egg-info sources during the installation

### ISSUE THREAD

**Issue by marekyggdrasil** [grinventions/secp256k1-zkp-mw#3]
I have examined the PR https://github.com/grinventions/secp256k1-zkp-mw/pull/2 and I found something odd.

When I publish the module I run the

```sh
python setup.py sdist
```

and it creates `dist/secp256k1-zkp-mw-<ver>.tar.gz`. There is a file in the archive `secp256k1_zkp_mw.egg-info/SOURCES.txt` and this file contains the absolute sources

```
/Users/marek/Development/open-source/grinventions/tmp3/secp256k1-zkp-mw/secp256k1-zkp/contrib/lax_der_parsing.c
/Users/marek/Development/open-source/grinventions/tmp3/secp256k1-zkp-mw/secp256k1-zkp/src/secp256k1.c
```

from my computer as the sdist is created on my computer. @NicolasFlamel1 has suggested to adjust the path to

```
secp256k1-zkp/contrib/lax_der_parsing.c
secp256k1-zkp/src/secp256k1.c
```

unfortunately this no longer works if installed from PyPi (it works if installed locally using `pip install .`). I published few versions to test it

https://test.pypi.org/project/secp256k1-zkp-mw/0.2.1/
https://test.pypi.org/project/secp256k1-zkp-mw/0.2.2/
https://test.pypi.org/project/secp256k1-zkp-mw/0.2.3/

This is something we need to investigate.

**Comment by marekyggdrasil** [comment]
The egg sources list are no longer absolute if these lines get changed

https://github.com/grinventions/secp256k1-zkp-mw/blob/d1484f855a5b5c670f3a6f34099b40b74c0ac194/build.py#L64-L65

to

```python
c_files = [
    'secp256k1-zkp/contrib/lax_der_parsing.c',
    'secp256k1-zkp/src/secp256k1.c'
]
```

**Comment by NicolasFlamel1** [comment]
@marekyggdrasil #4 should fix this issue. It uses a `MANIFEST.in` file to remove the absolute paths from `SOURCES.txt` when the module is being packaged.

With this change, I was able to successfully install the module with `pip install .`, package the module with`python setup.py sdist`, and install the module from PyPi with `pip install -i https://test.pypi.org/simple/ secp256k1-zkp-mw-nf` on Windows, macOS, and Linux.

**Comment by marekyggdrasil** [comment]
@NicolasFlamel1 I published https://pypi.org/project/secp256k1-zkp-mw/0.3.0/ could you run
```sh
pip install secp256k1-zkp-mw==0.3.0
```
on your Windows machine just to double check?

**Comment by NicolasFlamel1** [comment]
@marekyggdrasil Just tested it on my Windows, macOS, and Linux machines. Install works and pytest passes all tests on all of them.
